// Code generated by protoc-gen-gogo.
// source: core.proto
// DO NOT EDIT!

/*
	Package rcchcore is a generated protocol buffer package.

	It is generated from these files:
		core.proto

	It has these top-level messages:
		PBHeader
		PBHeaders
		PBRequestInfo
		PBResponseInfo
		PBErrorTrace
*/
package rcchcore

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type RequestType int32

const (
	RequestType_UNKNOW_REQUEST RequestType = 0
	RequestType_QUERY          RequestType = 1
	RequestType_EXECUTE        RequestType = 2
	RequestType_MESSAGE        RequestType = 3
)

var RequestType_name = map[int32]string{
	0: "UNKNOW_REQUEST",
	1: "QUERY",
	2: "EXECUTE",
	3: "MESSAGE",
}
var RequestType_value = map[string]int32{
	"UNKNOW_REQUEST": 0,
	"QUERY":          1,
	"EXECUTE":        2,
	"MESSAGE":        3,
}

func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}
func (RequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptorCore, []int{0} }

type ResponseType int32

const (
	ResponseType_UNKNOW_RESPONSE ResponseType = 0
	ResponseType_RESPONSE        ResponseType = 1
	ResponseType_ACK             ResponseType = 2
	ResponseType_PUSH            ResponseType = 3
)

var ResponseType_name = map[int32]string{
	0: "UNKNOW_RESPONSE",
	1: "RESPONSE",
	2: "ACK",
	3: "PUSH",
}
var ResponseType_value = map[string]int32{
	"UNKNOW_RESPONSE": 0,
	"RESPONSE":        1,
	"ACK":             2,
	"PUSH":            3,
}

func (x ResponseType) String() string {
	return proto.EnumName(ResponseType_name, int32(x))
}
func (ResponseType) EnumDescriptor() ([]byte, []int) { return fileDescriptorCore, []int{1} }

type PBHeader struct {
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Data  []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *PBHeader) Reset()                    { *m = PBHeader{} }
func (m *PBHeader) String() string            { return proto.CompactTextString(m) }
func (*PBHeader) ProtoMessage()               {}
func (*PBHeader) Descriptor() ([]byte, []int) { return fileDescriptorCore, []int{0} }

type PBHeaders struct {
	Header []*PBHeader `protobuf:"bytes,1,rep,name=header" json:"header,omitempty"`
}

func (m *PBHeaders) Reset()                    { *m = PBHeaders{} }
func (m *PBHeaders) String() string            { return proto.CompactTextString(m) }
func (*PBHeaders) ProtoMessage()               {}
func (*PBHeaders) Descriptor() ([]byte, []int) { return fileDescriptorCore, []int{1} }

type PBRequestInfo struct {
	ID     uint64      `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Target string      `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Path   string      `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Type   RequestType `protobuf:"varint,4,opt,name=type,proto3,enum=rcchcore.RequestType" json:"type,omitempty"`
}

func (m *PBRequestInfo) Reset()                    { *m = PBRequestInfo{} }
func (m *PBRequestInfo) String() string            { return proto.CompactTextString(m) }
func (*PBRequestInfo) ProtoMessage()               {}
func (*PBRequestInfo) Descriptor() ([]byte, []int) { return fileDescriptorCore, []int{2} }

type PBResponseInfo struct {
	RequestID uint64       `protobuf:"varint,1,opt,name=RequestID,json=requestID,proto3" json:"RequestID,omitempty"`
	HasError  bool         `protobuf:"varint,2,opt,name=has_error,json=hasError,proto3" json:"has_error,omitempty"`
	Type      ResponseType `protobuf:"varint,3,opt,name=type,proto3,enum=rcchcore.ResponseType" json:"type,omitempty"`
}

func (m *PBResponseInfo) Reset()                    { *m = PBResponseInfo{} }
func (m *PBResponseInfo) String() string            { return proto.CompactTextString(m) }
func (*PBResponseInfo) ProtoMessage()               {}
func (*PBResponseInfo) Descriptor() ([]byte, []int) { return fileDescriptorCore, []int{3} }

type PBErrorTrace struct {
	Port string `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	Err  string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (m *PBErrorTrace) Reset()                    { *m = PBErrorTrace{} }
func (m *PBErrorTrace) String() string            { return proto.CompactTextString(m) }
func (*PBErrorTrace) ProtoMessage()               {}
func (*PBErrorTrace) Descriptor() ([]byte, []int) { return fileDescriptorCore, []int{4} }

func init() {
	proto.RegisterType((*PBHeader)(nil), "rcchcore.PBHeader")
	proto.RegisterType((*PBHeaders)(nil), "rcchcore.PBHeaders")
	proto.RegisterType((*PBRequestInfo)(nil), "rcchcore.PBRequestInfo")
	proto.RegisterType((*PBResponseInfo)(nil), "rcchcore.PBResponseInfo")
	proto.RegisterType((*PBErrorTrace)(nil), "rcchcore.PBErrorTrace")
	proto.RegisterEnum("rcchcore.RequestType", RequestType_name, RequestType_value)
	proto.RegisterEnum("rcchcore.ResponseType", ResponseType_name, ResponseType_value)
}
func (m *PBHeader) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *PBHeader) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintCore(data, i, uint64(len(m.Name)))
		i += copy(data[i:], m.Name)
	}
	if len(m.Value) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintCore(data, i, uint64(len(m.Value)))
		i += copy(data[i:], m.Value)
	}
	if len(m.Data) > 0 {
		data[i] = 0x1a
		i++
		i = encodeVarintCore(data, i, uint64(len(m.Data)))
		i += copy(data[i:], m.Data)
	}
	return i, nil
}

func (m *PBHeaders) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *PBHeaders) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Header) > 0 {
		for _, msg := range m.Header {
			data[i] = 0xa
			i++
			i = encodeVarintCore(data, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(data[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *PBRequestInfo) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *PBRequestInfo) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ID != 0 {
		data[i] = 0x8
		i++
		i = encodeVarintCore(data, i, uint64(m.ID))
	}
	if len(m.Target) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintCore(data, i, uint64(len(m.Target)))
		i += copy(data[i:], m.Target)
	}
	if len(m.Path) > 0 {
		data[i] = 0x1a
		i++
		i = encodeVarintCore(data, i, uint64(len(m.Path)))
		i += copy(data[i:], m.Path)
	}
	if m.Type != 0 {
		data[i] = 0x20
		i++
		i = encodeVarintCore(data, i, uint64(m.Type))
	}
	return i, nil
}

func (m *PBResponseInfo) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *PBResponseInfo) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.RequestID != 0 {
		data[i] = 0x8
		i++
		i = encodeVarintCore(data, i, uint64(m.RequestID))
	}
	if m.HasError {
		data[i] = 0x10
		i++
		if m.HasError {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.Type != 0 {
		data[i] = 0x18
		i++
		i = encodeVarintCore(data, i, uint64(m.Type))
	}
	return i, nil
}

func (m *PBErrorTrace) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *PBErrorTrace) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Port) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintCore(data, i, uint64(len(m.Port)))
		i += copy(data[i:], m.Port)
	}
	if len(m.Err) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintCore(data, i, uint64(len(m.Err)))
		i += copy(data[i:], m.Err)
	}
	return i, nil
}

func encodeFixed64Core(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Core(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintCore(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (m *PBHeader) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovCore(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovCore(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovCore(uint64(l))
	}
	return n
}

func (m *PBHeaders) Size() (n int) {
	var l int
	_ = l
	if len(m.Header) > 0 {
		for _, e := range m.Header {
			l = e.Size()
			n += 1 + l + sovCore(uint64(l))
		}
	}
	return n
}

func (m *PBRequestInfo) Size() (n int) {
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovCore(uint64(m.ID))
	}
	l = len(m.Target)
	if l > 0 {
		n += 1 + l + sovCore(uint64(l))
	}
	l = len(m.Path)
	if l > 0 {
		n += 1 + l + sovCore(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovCore(uint64(m.Type))
	}
	return n
}

func (m *PBResponseInfo) Size() (n int) {
	var l int
	_ = l
	if m.RequestID != 0 {
		n += 1 + sovCore(uint64(m.RequestID))
	}
	if m.HasError {
		n += 2
	}
	if m.Type != 0 {
		n += 1 + sovCore(uint64(m.Type))
	}
	return n
}

func (m *PBErrorTrace) Size() (n int) {
	var l int
	_ = l
	l = len(m.Port)
	if l > 0 {
		n += 1 + l + sovCore(uint64(l))
	}
	l = len(m.Err)
	if l > 0 {
		n += 1 + l + sovCore(uint64(l))
	}
	return n
}

func sovCore(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozCore(x uint64) (n int) {
	return sovCore(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PBHeader) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PBHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PBHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCore
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCore
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCore
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], data[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCore(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PBHeaders) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PBHeaders: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PBHeaders: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCore
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Header = append(m.Header, &PBHeader{})
			if err := m.Header[len(m.Header)-1].Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCore(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PBRequestInfo) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PBRequestInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PBRequestInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.ID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Target", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCore
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Target = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCore
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Type |= (RequestType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCore(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PBResponseInfo) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PBResponseInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PBResponseInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestID", wireType)
			}
			m.RequestID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.RequestID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasError", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasError = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Type |= (ResponseType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCore(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PBErrorTrace) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PBErrorTrace: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PBErrorTrace: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Port", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCore
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Port = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Err", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCore
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Err = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCore(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCore(data []byte) (n int, err error) {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCore
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCore
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if data[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCore
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthCore
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowCore
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := data[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipCore(data[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthCore = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCore   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("core.proto", fileDescriptorCore) }

var fileDescriptorCore = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x92, 0x51, 0x6f, 0xd3, 0x30,
	0x14, 0x85, 0xeb, 0x24, 0xeb, 0x92, 0xdb, 0x52, 0xac, 0xcb, 0x98, 0x22, 0x40, 0x55, 0xd5, 0xa7,
	0xd2, 0x87, 0x22, 0x0d, 0x24, 0x9e, 0xd7, 0xd5, 0xd0, 0x69, 0xa2, 0xcb, 0x9c, 0x46, 0xc0, 0xd3,
	0x64, 0x3a, 0xd3, 0x20, 0x41, 0x1d, 0x1c, 0x6f, 0x68, 0xff, 0x70, 0x8f, 0xfc, 0x04, 0xe8, 0x2f,
	0x41, 0x76, 0x93, 0x92, 0xb7, 0x73, 0x6e, 0x4e, 0xfc, 0x1d, 0x5f, 0x19, 0x60, 0xa5, 0xb4, 0x9c,
	0x14, 0x5a, 0x19, 0x85, 0xa1, 0x5e, 0xad, 0x72, 0xeb, 0x9f, 0x1d, 0xad, 0xd5, 0x5a, 0xb9, 0xe1,
	0x2b, 0xab, 0x76, 0xdf, 0x87, 0x73, 0x08, 0x93, 0xe9, 0x5c, 0x8a, 0x1b, 0xa9, 0x11, 0x21, 0xd8,
	0x88, 0x1f, 0x32, 0x26, 0x03, 0x32, 0x8a, 0xb8, 0xd3, 0x78, 0x04, 0x07, 0x77, 0xe2, 0xfb, 0xad,
	0x8c, 0x3d, 0x37, 0xdc, 0x19, 0x9b, 0xbc, 0x11, 0x46, 0xc4, 0xfe, 0x80, 0x8c, 0xba, 0xdc, 0xe9,
	0xe1, 0x5b, 0x88, 0xea, 0x93, 0x4a, 0x1c, 0x43, 0x3b, 0x77, 0x32, 0x26, 0x03, 0x7f, 0xd4, 0x39,
	0xc1, 0x49, 0xdd, 0x63, 0x52, 0x87, 0x78, 0x95, 0x18, 0xde, 0xc1, 0xa3, 0x64, 0xca, 0xe5, 0xcf,
	0x5b, 0x59, 0x9a, 0xf3, 0xcd, 0x57, 0x85, 0x3d, 0xf0, 0xce, 0x67, 0xae, 0x45, 0xc0, 0xbd, 0x6f,
	0x33, 0x3c, 0x86, 0xb6, 0x11, 0x7a, 0x2d, 0x4d, 0x55, 0xa2, 0x72, 0xb6, 0x45, 0x21, 0x4c, 0xee,
	0x5a, 0x44, 0xdc, 0x69, 0x7c, 0x09, 0x81, 0xb9, 0x2f, 0x64, 0x1c, 0x0c, 0xc8, 0xa8, 0x77, 0xf2,
	0xf4, 0x3f, 0xb6, 0x02, 0x2c, 0xef, 0x0b, 0xc9, 0x5d, 0x64, 0xf8, 0x0b, 0x7a, 0x96, 0x5b, 0x16,
	0x6a, 0x53, 0x4a, 0x07, 0x7e, 0x01, 0x51, 0xdd, 0xa3, 0xe6, 0x47, 0xba, 0x1e, 0xe0, 0x73, 0x88,
	0x72, 0x51, 0x5e, 0x4b, 0xad, 0x95, 0x76, 0x4d, 0x42, 0x1e, 0xe6, 0xa2, 0x64, 0xd6, 0xe3, 0xb8,
	0xe2, 0xfa, 0x8e, 0x7b, 0xdc, 0xe4, 0xee, 0x00, 0x0d, 0xf0, 0x1b, 0xe8, 0x26, 0x53, 0xf7, 0xdb,
	0x52, 0x8b, 0x95, 0xdb, 0x66, 0xa1, 0xb4, 0xa9, 0xf7, 0x6e, 0x35, 0x52, 0xf0, 0xa5, 0xd6, 0xd5,
	0x85, 0xad, 0x1c, 0xbf, 0x83, 0x4e, 0xe3, 0x0e, 0x88, 0xd0, 0xcb, 0x16, 0x17, 0x8b, 0xcb, 0x8f,
	0xd7, 0x9c, 0x5d, 0x65, 0x2c, 0x5d, 0xd2, 0x16, 0x46, 0x70, 0x70, 0x95, 0x31, 0xfe, 0x99, 0x12,
	0xec, 0xc0, 0x21, 0xfb, 0xc4, 0xce, 0xb2, 0x25, 0xa3, 0x9e, 0x35, 0x1f, 0x58, 0x9a, 0x9e, 0xbe,
	0x67, 0xd4, 0x1f, 0xcf, 0xa0, 0xdb, 0xec, 0x84, 0x4f, 0xe0, 0xf1, 0xfe, 0xa0, 0x34, 0xb9, 0x5c,
	0xa4, 0x8c, 0xb6, 0xb0, 0x0b, 0xe1, 0xde, 0x11, 0x3c, 0x04, 0xff, 0xf4, 0xec, 0x82, 0x7a, 0x18,
	0x42, 0x90, 0x64, 0xe9, 0x9c, 0xfa, 0x53, 0xfa, 0xf0, 0xb7, 0xdf, 0x7a, 0xd8, 0xf6, 0xc9, 0xef,
	0x6d, 0x9f, 0xfc, 0xd9, 0xf6, 0xc9, 0x97, 0xb6, 0x7b, 0x50, 0xaf, 0xff, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x30, 0xd0, 0x02, 0x24, 0x7e, 0x02, 0x00, 0x00,
}
